### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [kenwmak/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by kenwmak** [comment]
I added ```<meta name="viewport" content="width=device-width, initial-scale=1.0">``` inside ```<head>```
https://github.com/kenwmak/splurty/commit/9c846165971cb2dbd277c490e08ae38abf39e51c it looks great on mobile now!

It seems like we should always include this if we are building with mobile in-mind, i.e. using ```col-xs-```, ```col-sm-```, etc. Is that right?

**Comment by kenmazaika** [comment]
Thumbs up!  And you're right, using `col-xs-` is important for mobile devices!

Awesome work, Ken!
